name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.15]
        java: [adopt@1.8, adopt@1.11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: olafurpg/setup-scala@v11
        with:
          java-version: ${{ matrix.java }}
      - name: Run tests
        run: sbt ++${{ matrix.scala }} test
      - name: Run scripted tests
        run: sbt ++${{ matrix.scala }} scripted